BLACK = (0, 0, 0)
BLUE = (90, 115, 190)
DARK_BLUE = (30, 60, 90)
GREY = (130, 130, 130)
LIGHT_BLUE = (60, 125, 180)
RED = (255, 0, 0)
WHITE = (255, 255, 255)

ACTION_FIND_ME = 'FIND_ME'
ACTION_GAME_STATE_CHANGED = 'GAME_STATE_CHANGED'
ACTION_HIT = 'HIT'
ACTION_MAKE_MOVE = 'MAKE_MOVE'
ACTION_MISS = 'MISS'
ACTION_MOVE = 'MOVE'
ACTION_SELECT_TEAM = 'SELECT_TEAM'
ACTION_STATUS = 'STATUS'
ACTION_WE_GOT_HIT = 'WE_GOT_HIT'
ACTION_WE_WERE_MISSED = 'WE_WERE_MISSED'

BUTTON_HEIGHT = 35
BORDER_SIZE = 30
CELL_SIZE = 50
GAME_SIZE = 10
HANDLED = True
HEADER_HEIGHT = 50
LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
NOT_HANDLED = False
SCREEN_WIDTH = 1140
SCREEN_HEIGHT = 800

MULTICAST_IP = '239.0.0.1'
MULTICAST_PORT = 10000

STATE_PREPARING = 'preparing'
STATE_OUR_TURN = 'our_turn'
STATE_THEIR_TURN = 'their_turn'
STATE_OUR_WIN = 'our_win'
STATE_THEIR_WIN = 'their_win'
